name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - name: Basic stats
        uses: lowlighter/metrics@366f8b9dfe3a59656c67d5dcad9950f59c9bc96d
        with:
          token: ${{ secrets.METRICS_TOKEN }}
      - name: Mildly interesting facts
        uses: lowlighter/metrics@366f8b9dfe3a59656c67d5dcad9950f59c9bc96d
        with:
          filename: metrics.plugin.habits.facts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no
          config_timezone: Europe/Berlin
      - name: Most used
        uses: lowlighter/metrics@366f8b9dfe3a59656c67d5dcad9950f59c9bc96d
        with:
          filename: metrics.plugin.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_limit: 4

